# Generated by Django 5.1.3 on 2024-11-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomokinyi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Service name')),
                ('description', models.TextField(verbose_name='About service')),
            ],
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='desicription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='short_desicription',
            new_name='short_description',
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(default='default.png', upload_to='clients'),
        ),
    ]
